# Site settings
title: Website về việc hỗ trợ những nông sản Việt Nam chưa có đầu ra.
email: giaicuunongsanviet.com@gmail.com
description: > Website về việc hỗ trợ những nông sản Việt Nam chưa có đầu ra.
baseurl: "http://giaicuunongsanviet.com" # the subpath of your site, e.g. /blog/
url: "http://giaicuunongsanviet.com" # the base hostname & protocol for your site
twitter_username: NhomTuThien
github_username:  NhomTuThien

# Build settings
markdown: kramdown

paginate: 4

author: NhomTuThien

gems: [jekyll-paginate]
