# Site settings
title: Giải cứu nông sản Việt.
email: giaicuunongsanviet.com@gmail.com
description: > #NULL
baseurl: "https://giaicuunongsanviet.github.io" # the subpath of your site, e.g. /blog/
url: "http://giaicuunongsanviet.github.io" # the base hostname & protocol for your site
twitter_username: NhomTuThien
github_username:  NhomTuThien
google_analytics: UA-92514619-1

# Build settings
markdown: kramdown

paginate: 4

author: NhomTuThien

gems: [jekyll-paginate]

